spring:
   application:
         name: ecom-config
   cloud:
     config:
      server:
           git:
            uri: file://D:/binil/gold/pack03/ch17/ch17-01/Ax2-Ecom-No-Security/config-repo

server:
  port: 8888

eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka/

#file:/home/myname/Ecom-WS/Ecom-NoSec/Ecom/config-repo
