spring:
  application:
    name: ecom-gateway
server:
  port: 9000

zuul:
  ignoredServices: '*'
  routes:
    ecom-core:
      path: /core/∗∗
      service-id: ecom-core
    ecom-user:
      path: /customer/∗∗
      service-id: ecom-user
    ecom-cart:
      path: /cart/∗∗
      service-id: ecom-cart
    ecom-product:
      path: /product/∗∗
      service-id: ecom-product
      stripPrefix: false
    ecom-history:
      path: /orderhistory/∗∗
      service-id: ecom-history
    ecom-delivery:
      path: /delivery/∗∗
      service-id: ecom-delivery
    ecom-shipping:
      path: /shipping/∗∗
      service-id: ecom-shipping

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
