spring:
  application:
    name: ecom-gateway
  cloud.config:
    failFast: true
    retry:
      initialInterval: 3000
      multiplier: 1.3
      maxInterval: 10000
      maxAttempts: 20
    uri: http://localhost:8888
server:
  port: 9000
#zuul:
#  ribbon:
#    eager-load:
#      enabled: true


